### ISSUE TITLE
Image display is not working with dynamic tf

### ISSUE THREAD

**Issue by vincentrou** [lucasw/rviz_textured_quads#5]
I think it is a nice feature in rviz. But for me, it is not working when I do not use static tf publisher.

**Comment by lucasw** [comment]
I tried this out with https://github.com/lucasw/rviz_interactive_tf and I also see it isn't working.

**Comment by lucasw** [comment]
Should be fixed now, thanks for pointing this out.

**Comment by vincentrou** [comment]
Yes thanks it works now. I do not know that ros::Time(0) had the effect to get the last tf transform.
